features=["trip_distance", "driver_distance", "event_hour", "driver_gps_accuracy", "is_rush_hour"]
target="is_completed"
test_size=0.2

[random_forest]
n_estimators=500
max_depth=40
min_samples_split=5
min_samples_leaf=2
n_jobs=-1
random_state=33
bootstrap=true
