features=["driver_gps_accuracy",
    "trip_distance",
    "hourofday",
    "hourofday_average",
    "driver_hourofday_average",
    "dayofweek",
    "dayofweek_average",
    "driver_dayofweek_average",
    "is_completed_last5day_rolling_mean",
    "driver_cluster_label",
    "customer_cluster_label"
    ]

target="is_completed"
test_size=0.2

[random_forest]
n_estimators=200
max_depth=32
n_jobs=-1
random_state=33
criterion='gini'
class_weight="balanced"